### ISSUE TITLE
Remove unnecessary optimizations

### ISSUE THREAD

**Issue by DerekGooding** [rushakh/Khi-Player#3]
The codebase looks like you learned to code from books written 10-years ago or came from a lower level language mind-set.

The C# compiler optimizes all the things you're trying to do. By manually calling the garbage collector, you're actually at best, slowing things down. 

You also don't need to null out everything. The extreme null handling here is crazy! Rozlinator catches like 600 warnings and 500 suggestions. All based on inefficient, worthless null handling. 

You have to look at dates when it comes to code optimization suggestions online. Something you need to remember about C#, it doesn't run what you type. The compiler takes what you type and creates performant code from it. All the hand curated "optimizations" get deleted by the compiler. C# is about readability. 

Also, if you're making things null because you WANT a crash/catch, throw an error. Don't make it nullable. 

I'm sorry you tried this 20 times. It looks like a labour of love. But you've been labouring in the completely wrong direction.

**Comment by rushakh** [comment]
Hello, thank you, I did actually learn some bare basics through C++ years ago (and some c# in 2014-15). I didn't know about C#'s behavior on this matter and am kinda mad about it now xDD (jk).
Don't worry about the 20 times thing, that was mostly to get things working not for optimization :D 
I guess I should now go remove those lines of code and see its effects. Thank you for the helpful feedback, it's much appreciated

**Comment by rushakh** [comment]
Cleaned the codes, removed unnecessary optimizations (and usage of the garbage collector), moved codes that changed the UI into the main form codes, and rewrote some of the codes that were missing (by mistake).
